server:
  port: 8081
spring:
  application:
    name: dianping
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://my-host:3306/dianping?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:123456}
  redis:
    host: my-host
    port: 6379
    password: ${REDIS_PWD:123456}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null    # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.example.dianping.entity # 别名扫描包

logging:
  level:
    com.example.dianping.controller: debug
    com.example.dianping.service: debug